"""adding author to games

Revision ID: 9a244021c12d
Revises: b8ee732efc69
Create Date: 2017-09-05 17:38:21.436350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a244021c12d'
down_revision = 'b8ee732efc69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('author', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'author')
    # ### end Alembic commands ###
