"""giving games res path

Revision ID: b8ee732efc69
Revises: 1db083b8d003
Create Date: 2017-09-05 15:03:10.602980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8ee732efc69'
down_revision = '1db083b8d003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('resource_path', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'games', ['resource_path'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='unique')
    op.drop_column('games', 'resource_path')
    # ### end Alembic commands ###
